---
name: Java CI with Maven
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Adjust Permissions
        run: sudo chmod -R a+rw /home/ubuntu/actions-runner/_work/Boardgame/Boardgame || true
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Compile with Maven
        run: mvn -B compile --file pom.xml
      - name: Test with Maven
        run: mvn -B test --file pom.xml
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        env:
          # actions/setup-java@v1 changes JAVA_HOME so it needs to be reset to match the depcheck image
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: BoardGame
          path: .
          format: 'XML'
          out: reports
          args: >
            --scan ./ --disableYarnAudit --disableNodeAudit --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          # path: ${{github.workspace}}/reports
          path: ../reports
          overwrite: true
      # - name: Run Trivy vulnerability scanner in repo mode
      #   uses: aquasecurity/trivy-action@0.20.0
      #   with:
      #     scan-type: 'fs'
      #     ignore-unfixed: true
      #     format: 'sarif'
      #     output: 'trivy-results.sarif'
      #     severity: 'CRITICAL'

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-results.sarif'

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.html'
          severity: 'CRITICAL'

      - name: Upload Trivy Results
        uses: actions/upload-artifact@v3
        with:
          name: Trivy-results
          path: trivy-results.html
          overwrite: true
      - name: Build with Maven
        run: mvn -B package --file pom.xml
