apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boardgame-deployment
  name: boardgame-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - name: boardgame
        ## image: pramod858/boardshack:v6
        image: pramod858/netflix:v14
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: boardgame
    k8s-app: boardgame
  name: boardgame
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: boardgame
